//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.28 at 12:59:12 PM EAT 
//


package ke.co.mmm.b2c.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MethodCall }
     * 
     */
    public MethodCall createMethodCall() {
        return new MethodCall();
    }

    /**
     * Create an instance of {@link MethodCall.Params }
     * 
     */
    public MethodCall.Params createMethodCallParams() {
        return new MethodCall.Params();
    }

    /**
     * Create an instance of {@link MethodCall.Params.Param }
     * 
     */
    public MethodCall.Params.Param createMethodCallParamsParam() {
        return new MethodCall.Params.Param();
    }

    /**
     * Create an instance of {@link MethodCall.Params.Param.Value }
     * 
     */
    public MethodCall.Params.Param.Value createMethodCallParamsParamValue() {
        return new MethodCall.Params.Param.Value();
    }

    /**
     * Create an instance of {@link MethodCall.Params.Param.Value.Struct }
     * 
     */
    public MethodCall.Params.Param.Value.Struct createMethodCallParamsParamValueStruct() {
        return new MethodCall.Params.Param.Value.Struct();
    }

    /**
     * Create an instance of {@link MethodCall.Params.Param.Value.Struct.Member }
     * 
     */
    public MethodCall.Params.Param.Value.Struct.Member createMethodCallParamsParamValueStructMember() {
        return new MethodCall.Params.Param.Value.Struct.Member();
    }

    /**
     * Create an instance of {@link MethodCall.Params.Param.Value2.Struct.Member.Value2 }
     * 
     */
    public MethodCall.Params.Param.Value.Struct.Member.Value2 createMethodCallParamsParamValueStructMemberValue() {
        return new MethodCall.Params.Param.Value.Struct.Member.Value2();
    }

}
